<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="19" tests="103" name="rsm.Cross_sell_Intrest_cost" time="472.618" errors="0" timestamp="2024-08-09T10:43:37 IST" skipped="0">
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Username" time="2.167"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Password" time="2.108"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Login_Button" time="20.089"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="SUBMIT_Button" time="3.091"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Click_On_Report" time="9.414"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Click_On_The_Cross_sell_Intrest" time="3.109"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Zone_Region_Wise" time="53.378"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Dealer_Parent_Group_Wise" time="71.705"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="workshop_Wise" time="71.655"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Day_Wise" time="71.501"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="service_Type_Wise" time="71.460"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_dispostion_Of_ZONE_Region_Wise_from__Dealer_Parent_Wise" time="1.009">
    <failure message="expected [8398] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8398] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_dispostion_Of_ZONE_Region_Wise_from__Dealer_Parent_Wise(Cross_sell_Intrest_cost.java:986)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_dispostion_Of_ZONE_Region_Wise_from__Dealer_Parent_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Worshop_Wise" time="1.010">
    <failure message="expected [8401] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8401] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Worshop_Wise(Cross_sell_Intrest_cost.java:992)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Worshop_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Day_Wise" time="1.014">
    <failure message="expected [8404] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8404] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Day_Wise(Cross_sell_Intrest_cost.java:998)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Day_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.007">
    <failure message="expected [8408] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [8408] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1004)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrest_dispostion_Of_ZONE_Region_Wise_from_Dealer_parent_group_Wise" time="1.007"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrest_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.012"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrest_dispostion_Of_ZONE_Region_Wise_from_Day_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrest_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.010">
    <failure message="expected [430] but found [429]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [430] but found [429]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_Intrest_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1029)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_Intrest_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.009">
    <failure message="expected [1350] but found [1349]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1350] but found [1349]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise(Cross_sell_Intrest_cost.java:1042)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Day_Wise" time="1.010">
    <failure message="expected [1350] but found [1349]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1350] but found [1349]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Day_Wise(Cross_sell_Intrest_cost.java:1048)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Day_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.004">
    <failure message="expected [1351] but found [1349]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1351] but found [1349]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1054)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_Intrest_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.011">
    <failure message="expected [6655] but found [6654]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [6655] but found [6654]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise(Cross_sell_Intrest_cost.java:1061)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.013">
    <failure message="expected [6657] but found [6654]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [6657] but found [6654]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise(Cross_sell_Intrest_cost.java:1067)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_workshop__Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Day_Wise" time="1.010">
    <failure message="expected [6660] but found [6654]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [6660] but found [6654]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Day_Wise(Cross_sell_Intrest_cost.java:1073)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Day_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.007">
    <failure message="expected [6662] but found [6654]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [6662] but found [6654]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1079)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Not_confiremed_dispostion_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.005"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.008"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested_Of_ZONE_Region_Wise_from_Day_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.015">
    <failure message="expected [0] but found [194]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0] but found [194]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_Intrested_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1105)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_Intrested_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.007"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.014"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES_Of_ZONE_Region_Wise_from_Day_Wise" time="1.010"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_GOLD_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_GOLD_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_GOLD_Of_ZONE_Region_Wise_from_Day_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_GOLD_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.013">
    <failure message="expected [45] but found [44]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [45] but found [44]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_GOLD_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_GOLD_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_PLATINUM_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.011"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_PLATINUM_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.014"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_PLATINUM_Of_ZONE_Region_Wise_from_Day_Wise" time="1.011"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_PLATINUM_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.011"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_PLATINUM_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.013"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_PLATINUM_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.008"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_PLATINUM_Of_ZONE_Region_Wise_from_Day_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_PLATINUM_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.010"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrested_sale2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrested_sale2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.007"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrested_sale2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.016"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrested_sale2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.017"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.007"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.013"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_Hydro_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_Hydro_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.011"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_Hydro_Of_ZONE_Region_Wise_from_Day_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_Hydro_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.007"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_FUEL_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_FUEL_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.019"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_FUEL_Of_ZONE_Region_Wise_from_Day_Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_FUEL_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.011"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_plus_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_plus_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_plus_Of_ZONE_Region_Wise_from_Day_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Ccp_plus_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.014"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested3_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.016"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested3_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested3_Of_ZONE_Region_Wise_from_Day_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_Intrested3_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.010">
    <failure message="expected [null] but found [0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [null] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_Total_Intrested3_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1357)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_Total_Intrested3_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Yes3_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.010"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Yes3_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.011"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Yes3_Of_ZONE_Region_Wise_from_Day_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Yes3_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.006"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Platinum2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.012"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Platinum2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.003"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Platinum2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.005"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Platinum2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.014"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare__Royal_Platinum2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_Platinum2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.003"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_Platinum2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.008"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Royal_Platinum2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.017"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare__Total_intrest_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.007"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrest_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.003"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrest_Of_ZONE_Region_Wise_from_Day_Wise" time="1.015"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_Total_intrest_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.016"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare__YES4_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.008"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES4_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.016"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES4_Of_ZONE_Region_Wise_from_Day_Wise" time="1.002"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_YES4_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.014"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare__CCP_Hydro2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.012"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_Hydro2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.013"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_Hydro2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.008"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_Hydro2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.003"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare__CCP_Fuel2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.002"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_Fuel2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.017"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_Fuel2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.009"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_Fuel2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.004"/>
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare__CCP_PLUS2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise" time="1.007">
    <failure message="expected [51] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [51] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare__CCP_PLUS2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise(Cross_sell_Intrest_cost.java:1539)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare__CCP_PLUS2_Of_ZONE_Region_Wise_from_Dealer_parent_Group_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_workshop__Wise" time="1.002">
    <failure message="expected [51] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [51] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_workshop__Wise(Cross_sell_Intrest_cost.java:1545)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_workshop__Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_Day_Wise" time="1.003">
    <failure message="expected [51] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [51] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_Day_Wise(Cross_sell_Intrest_cost.java:1551)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_Day_Wise -->
  <system-out/>
  <testcase classname="rsm.Cross_sell_Intrest_cost" name="Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_Service_Type_Wise" time="1.035">
    <failure message="expected [51] but found [8397]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [51] but found [8397]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at rsm.Cross_sell_Intrest_cost.Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_Service_Type_Wise(Cross_sell_Intrest_cost.java:1557)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Compare_CCP_PLUS2_Of_ZONE_Region_Wise_from_Service_Type_Wise -->
  <system-out/>
</testsuite> <!-- rsm.Cross_sell_Intrest_cost -->
